### ISSUE TITLE
URL not displayed in publication entry

### ISSUE THREAD

**Issue by samvanstroud** [sinaatalay/RenderCV#138]
**Describe the bug**
When adding the field `url` to a `PublicationEntry`, no URL is displayed. I would expect to see a hyperlinked URL here, similar to when using a DOI. If `disable_external_link_icons: true`, then the link dissappears entirely.

**To Reproduce**
```yaml
    publications:
      - title: 3D Finite Element Analysis of No-Insulation Coils
        authors:
          - Frodo Baggins
          - '***John Doe***'
          - Samwise Gamgee
        url: https://github.com/
        date: 2004-01
```

**Screenshots**
<img width="539" alt="Screenshot 2024-07-23 at 13 40 07" src="https://github.com/user-attachments/assets/2d0e3dc7-6656-41b3-a532-b5b3c4a1c179">
