### ISSUE TITLE
Filter on content or sections

### ISSUE THREAD

**Issue by akib1689** [sinaatalay/RenderCV#164]
### Discussed in https://github.com/sinaatalay/rendercv/discussions/163

<sub>Originally posted by **akib1689** on August 29, 2024</sub>

---

I don't know if I'm missing something or not. It would be great if we could hide/include some of the sections from the YAML file.

**My Use Case:**

I apply for 2-3 roles, and each time I need to manually comment/uncomment the relevant portion of the YAML file. It would be very useful if we had something like a tag in each item.

> [!NOTE] 
> Each section will have some tags. For example, one of my skill rows should be included for DevOps-related jobs but not for developer-related jobs. It would be really helpful to set a match tag from the command line, say "devops," and each node that has the tag "devops" would be included in that particular render of the CV. By default, it would include all the contents.

The implementation can be flexible. But here I'm providing one way to implement:

- Each element in our yaml file will have an optional field named `tag`
- This `tag` will be an array of strings.
- Every child element will have parents tag nested format unless they choose to ignore it. one liner currently has one line string then have 2 things say `content`, `tag`  
- Then in cli will have some command line argument say `match-tag` or `include-tag` to include only those nodes that has the that tag attached to them.

**Comment by akib1689** [comment]
I think we should discuss how do implement this section. Here is my proposal:

- Each of the entry types in render cv should have an optional field named `label`. 
- The sections are pre defined. or We can also make the whole section tag able like this. Then we can include whole section by that label. For my case It would be say publications. For job seeking I don't like to include publications section. I need it only for university application. 
-  Contrary to the second point, we might have a business logic that is if the entry of any of the section becomes 0, Then don't include the section. Either one is fine for me.

```yaml
rendercv_settings:
  cli_options: # might be called render options also
    dont_generate_png: true
    # ... other cli options to implement
  versions:
    # array of different version
    - label1:
      include:
        labels: label1  # parses all the contents and its sub contents labled devops only.
```

**Comment by sinaatalay** [comment]
The `cv` field of the YAML input file should be used only for content-writing purposes. Whatever is in there should be the stuff that is meant to be printed in the PDF. What about something like this?

```yaml
rendercv_settings:
  hidden_sections:
    - Publications
```

**Comment by akib1689** [comment]
Sorry, for not getting back to you, I would like this then:

```yaml
rendercv_settings:
  versions:
    - devops:
      - experience.exp1
      - experience.exp2
    - research:
      - experience.exp2
      - experience.exp3
```

Finally `rendercv render --version devops`

**Comment by ce603** [comment]
Hi, I would also be interested in a feature like this, but more similar to the way that @akib1689 originally described. I would prefer to be able to filter each individual line by a tag (or as @akib1689 described, a "label"), rather than use either of the proposed solutions. 

I have a few reasons for wanting this:

First, although my primary career track is in IT, I have a strong interest in finance. When I apply to finance jobs, there are certain highlights I want to emphasize. For other jobs, I would use a different phrasing to emphasize the IT aspects, or exclude the highlight altogether. I'm referring to individual bullet points here, not entire sections.

Second, I struggle with interviews. I would like having notes below each highlight that I can make visible when I print my copy of the resume for the interview. This way, when the interviewer asks, "it says here on your resume that you're familiar with encryption, can you talk about that?" I can find the point he's referring to on his abridged resume and use the bullet points on my copy to jog my memory. I would list specific examples of things I did related to that bullet point.

Finally, I could also see myself wanting to hide/show entire sections like publications for non-academic jobs.

Since "label" is already used and printed in the document, I would prefer to use the word "tag" or "filter". With this, the .yaml file would look something like this:

```
cv:
  sections:
    highlights:
      - bullet: "A major accomplishment I did."
      - bullet: 'Developed web application using Flask and NumPy to track financial metrics, '
        tag: IT
      - bullet: 'Tracked ROI, Volatility, and DTE using a web application I built.'
        tag: Finance
      - bullet: 'Developed $2M multifamily apartment building.'
        tag: Finance

    technologies:
      - label: Encryption & Security
        description: Encryption, BitLocker, PGP
      - label: Encryption & Security Notes
        description: Talk about public key infrastructure, experience with HIPAA compliance, mbam client you configured in Active Directory...
        tag: Notes 

rendercv_settings:
  tags:
    hide_tags: IT, Notes

```

This would result in the following output:

### Highlights
- A major accomplishment I did.
- Tracked ROI, Volatility, and DTE using a web application I built.
- Developed $2M multifamily apartment building.

### Technologies
- **Encryption & Security:** Encryption, BitLocker, PGP

----------------------
On the other hand, if I used something like:

```
rendercv_settings:
  tags:
    hide_tags: Finance
```

The output would be:

### Highlights
- A major accomplishment I did.
- Developed web application using Flask and NumPy to track financial metrics, 

### Technologies
- **Encryption & Security:** Encryption, BitLocker, PGP
- **Encryption & Security Notes:** Talk about public key infrastructure, experience with HIPAA compliance, mbam client...

---------------------

**Comment by ce603** [comment]
A few more comments:

1. I can see myself adding multiple tags to a single entry, e.g.
```
cv:
  sections:
    highlights:
      - bullet: "An industry-specific accomplishment I did."
        tags: IT, Education
```

2. You should be able to use a tag to hide an entire section, provided it is at the same indentation level. Below would hide the "Publications" section:
```
cv:
  sections:
    publications:
      - title: Magneto-Thermal Thin Shell Approximation for 3D Finite Element Analysis of No-Insulation Coils
        authors:
          - John Doe
          - Jane Doe
    tags: Education
```

3. I can see people wanting to create a `show_tags` filter, which would show anything untagged plus only the entries listed. For example
```
rendercv_settings:
  tags:
    show_tags: Finance
```

would output only untagged items and items tagged as finance. 

4. I think having a "show_tag_labels" or something similar for the tags: property would be helpful for when you want to see every version of your resume at once. The default value would be false. 
```
rendercv_settings:
  tags:
    show_tag_labels: true
```

This would actually include the word before the description with a colored background or something. For example, including `show_tag_labels: true` would would produce output like:

### Highlights
- A major accomplishment I did.
- _[IT]_ Developed web application using Flask and NumPy to track financial metrics, 
- _[Finance]_ Tracked ROI, Volatility, and DTE using a web application I built.
- _[Finance]_ Developed $2M multifamily apartment building.

### Technologies
- Encryption & Security: Encryption, BitLocker, PGP
- _[Notes]_ Encryption & Security Notes: Talk about public key infrastructure, experience with HIPAA compliance, mbam client...

### _[Education]_ Publications
- Magneto-Thermal Thin Shell Approximation for 3D Finite Element Analysis of No-Insulation Coils by John Doe & Jane Doe.

Thoughts?

**Comment by ce603** [comment]
Also, I want to point out that the solution below does not provide the ability to hide individual highlights/bullet points

```
rendercv_settings:
  hidden_sections:
    - Publications
```

And the solution below is susceptible to errors if you move sections around on your resume. If you start a new job, for example, now all of your experience.expN values need to be incremented by 1. It seems much better to reference it by a named value, rather than an index number. But I am not a fan of editing this in a different part of the document where you can't see exactly what it's surrounded with. 

```
rendercv_settings:
  versions:
    - devops:
      - experience.exp1
      - experience.exp2
    - research:
      - experience.exp2
      - experience.exp3
```

@sinaatalay, is there a broad-level reason that I'm missing as to why meta-data should not be included in the `cv:` section? Perhaps you're thinking of something I'm not.

**Comment by akib1689** [comment]
@sinaatalay I forgot some procedure. Do the fontawesome needed to be installed in the machine to work? cause when I used the use icons for connections then it broke

I installed this with:

`pip install "rendercv[full]"`

**Comment by elaske** [comment]
@sinaatalay I wanted to second  @akib1689's original thought and the rationale is as @ce603 noted above. For me, the most important reason to build a data model of content for my CV is such that I can do things with it that are not enabled by any other tool. I understand the concept was just that this eases rendering, but the power of the data model is: 

1. Stop maintaining multiple copies / versions of CV content. Eliminate copy-pasting, propagating, and keeping coherence between different versions of the CV.
2. To quickly / easily generate multiple outputs based on tuning or filtering content - this is usually the most time-consuming when applying to different types of roles to stress different experiences as @ce603 notes.
3. Generating multiple outputs from the same source data, in different themes or formats (e.g., PDF, HTML, Markdown)

Without these goals, there's only marginal value of YAML definition of the content over just having Typst or LaTeX files in a git repo. JSONResume has additional value-add items, for comparison.

The method that @akib1689 suggested was the one that I had in mind when I was contemplating using a YAML Format.

Another use for this would be in optimizing for page-count as you could use tags for prioritization of highlights / bullets.

Another concept for enabling this support which could also enable additional features is to use a non-standard `yaml` include / importing, e.g. `!include "highlights.yml"` or some other method to "dynamically" assemble the data model that will be rendered. This can also just generally be supported by a more flexible scripting invocation.

**Comment by akib1689** [comment]
I am working on this weekend. already I implemented the filtering on section. But with the highlights and text entry. current implementation is like this:

```yaml
skills:
  - skill 1, skill 2. etc.
```

New, implementation would be like this:

```yaml
skills:
  - content: skill 1, skill 2
  - tags: [tag1, tag2]
```

This is a breaking change. And I'm trying to figure out how to support this backwards compatibility.

**Comment by akib1689** [comment]
@sinaatalay Please suggest preference how this should be implemented.

**Comment by elaske** [comment]
1) I don't think it would be a breaking change if you're adding another
field to the yaml. There's already arbitrary key support.

2) I would think the loosely coupled tag and item list is not a good
approach, as they can become mismatched easily.

Note: Doing a tightly coupled approach May very well be breaking.

Just my first thoughts as someone who wants to see this feature (and
thought about contributing it if I get a chance to work on it).

**Comment by ce603** [comment]
@akib1689:

I don't think tags should have their own `-`. 

```
#akib1689 code

skills:
  - content: skill 1, skill 2
  - tags: [tag1, tag2]
```

Assuming it looks like the rest of the yaml file, it should look like:

```
skills:
  - content: skill 1, skill 2
    tags: [tag1, tag2]
```

The tags go with `content`. It's just another attribute, like `details` or `position` or `start_date`...
