### ISSUE TITLE
Allow nested bullet points

### ISSUE THREAD

**Issue by amarvin** [sinaatalay/RenderCV#177]
Would it be possible to have nested bulleted lists? I often put sub-bullets in my work experience like:

#### MyCompany
- Project A
  - Deliverable 1
  - Deliverable 2
- Project B
  - Challenge 1
  - Deliverable 3

I tried to do this with `rendercv` using:

```yml
    experience:
      - company: MyCompany
        position: MyJob
        start_date: 2024-09
        highlights:
          - Project 1
            - Deliverable 1
            - Deliverable 2
          - Project 2
            - Challenge 1
            - Deliverable 3
```

but it renders as:

![image](https://github.com/user-attachments/assets/a5c13ff5-a2ae-43f8-a3f6-56dd79e0aa69)

I also tried using markdown:

```yml
    experience:
      - company: MyCompany
        position: MyJob
        start_date: 2024-09
        highlights:
          - "Project 1
            - Deliverable 1
            - Deliverable 2"
          - "Project 2
            - Challenge 1
            - Deliverable 3"
```

but got the same render.

**Comment by amarvin** [comment]
Here's my workaround so far:

```yml
    experience:
      - company: MyCompany
        position: MyJob
        start_date: 2024-09
        highlights:
          - "Project 1
            \\begin{itemize}
              \\item Deliverable 1
              \\item Deliverable 2
            \\end{itemize}"
          - "Project 2
            \\begin{itemize}
              \\item Challenge 1
              \\item Deliverable 3
            \\end{itemize}"
```

which renders as:

![image](https://github.com/user-attachments/assets/61cddb13-946b-4feb-aa87-59d142c9c208)

Note that I needed extra backslashes to escape the backslash LaTeX commands (https://stackoverflow.com/questions/32991517/how-to-escape-colons-and-other-special-characters-in-a-yaml-string).

**Comment by sinaatalay** [comment]
Thank you, that's a good idea. We should implement this.

**Comment by aaronk1** [comment]
Thanks, @amarvin . I want to do something similar with separate roles same company.

**Comment by THEAccess** [comment]
> Here's my workaround so far:
> 
>     experience:
>       - company: MyCompany
>         position: MyJob
>         start_date: 2024-09
>         highlights:
>           - "Project 1
>             \\begin{itemize}
>               \\item Deliverable 1
>               \\item Deliverable 2
>             \\end{itemize}"
>           - "Project 2
>             \\begin{itemize}
>               \\item Challenge 1
>               \\item Deliverable 3
>             \\end{itemize}"
> 
> which renders as:
> 
> ![image](https://github.com/user-attachments/assets/61cddb13-946b-4feb-aa87-59d142c9c208)
> 
> Note that I needed extra backslashes to escape the backslash LaTeX commands (https://stackoverflow.com/questions/32991517/how-to-escape-colons-and-other-special-characters-in-a-yaml-string).

This worked before 2.0. Any idea how to get this working with typst?

**Comment by amarvin** [comment]
> > Here's my workaround so far:
> > ```
> > experience:
> >   - company: MyCompany
> >     position: MyJob
> >     start_date: 2024-09
> >     highlights:
> >       - "Project 1
> >         \\begin{itemize}
> >           \\item Deliverable 1
> >           \\item Deliverable 2
> >         \\end{itemize}"
> >       - "Project 2
> >         \\begin{itemize}
> >           \\item Challenge 1
> >           \\item Deliverable 3
> >         \\end{itemize}"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which renders as:
> > ![image](https://github.com/user-attachments/assets/61cddb13-946b-4feb-aa87-59d142c9c208)
> > Note that I needed extra backslashes to escape the backslash LaTeX commands (https://stackoverflow.com/questions/32991517/how-to-escape-colons-and-other-special-characters-in-a-yaml-string).
> 
> This worked before 2.0. Any idea how to get this working with typst?

`rendercv==2.0` switched from LaTeX to Typst, so the syntax for lists changed. I've been trying to get this working myself and haven't found a solution. I plan to continue using `rendercv==1.18`.

**Comment by THEAccess** [comment]
> > > Here's my workaround so far:
> > > ```
> > > experience:
> > >   - company: MyCompany
> > >     position: MyJob
> > >     start_date: 2024-09
> > >     highlights:
> > >       - "Project 1
> > >         \\begin{itemize}
> > >           \\item Deliverable 1
> > >           \\item Deliverable 2
> > >         \\end{itemize}"
> > >       - "Project 2
> > >         \\begin{itemize}
> > >           \\item Challenge 1
> > >           \\item Deliverable 3
> > >         \\end{itemize}"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > which renders as:
> > > ![image](https://github.com/user-attachments/assets/61cddb13-946b-4feb-aa87-59d142c9c208)
> > > Note that I needed extra backslashes to escape the backslash LaTeX commands (https://stackoverflow.com/questions/32991517/how-to-escape-colons-and-other-special-characters-in-a-yaml-string).
> > 
> > 
> > This worked before 2.0. Any idea how to get this working with typst?
> 
> `rendercv==2.0` switched from LaTeX to Typst, so the syntax for lists changed. I've been trying to get this working myself and haven't found a solution. I plan to continue using `rendercv==1.18`.

Yes, I have to do the same for now. Bullet points within a section are a fundamental feature. I had professional CV reviewers recommend this because it significantly improves readability.

**Comment by amaanansari** [comment]
Any progress or workarounds for rendercv >= 2.0 so far?

**Comment by sinaatalay** [comment]
This will be possible in the next release.

**Comment by sinaatalay** [comment]
Nested bullet points are now possible in v2.2 with indented highlights like this:

```yaml
cv:
  sections:
    education:
      - institution: Stanford University
        area: Computer Science
        degree: PhD
        date:
        start_date: 2023-09
        end_date: present
        location: Stanford, CA, USA
        highlights:
          - Working on the optimization of autonomous vehicles in urban environments
            - Published [5 peer-reviewed research papers](https://example.com)
```

**Comment by lamdavid759** [comment]
I've really been loving this project, and this is probably the one minor quibble I have. +1 for this being a useful feature I'd love to have!

**Comment by sinaatalay** [comment]
Nested bullet points with a really nice syntax will be available in the next release. Thank you for your suggestions!

**Comment by mkbhuiyan96** [comment]
Any estimate on when this would come out?

**Comment by sinaatalay** [comment]
We plan to release a new version in a week.

**Comment by bhaveshs6** [comment]
Hi Sina Atalay,

I noticed that the nested_bullet property is defined in the schema.json under rendercv__themes__engineeringclassic__Highlights. However, when I attempt to include nested_bullet in the design.highlights section of my YAML configuration, I encounter the following error:

┏━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Location                                        ┃ Input Value  ┃ Error Message                                                                          ┃
┡━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
 │ design.highlights.nested_bullet.   │ ◦                      │ This field is unknown for this object! Please remove it.            │
└───────────────┴──────┴────────────────────────────┘

Theme being used is engineeringclassic

Could you please confirm if nested_bullet is currently supported? Thank you!

**Comment by amarvin** [comment]
> Hi Sina Atalay,
> 
> I noticed that the nested_bullet property is defined in the schema.json under rendercv__themes__engineeringclassic__Highlights. However, when I attempt to include nested_bullet in the design.highlights section of my YAML configuration, I encounter the following error:
> 
> ┏━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┃ Location ┃ Input Value ┃ Error Message ┃ ┡━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │ design.highlights.nested_bullet. │ ◦ │ This field is unknown for this object! Please remove it. │ └───────────────┴──────┴────────────────────────────┘
> 
> Theme being used is engineeringclassic
> 
> Could you please confirm if nested_bullet is currently supported? Thank you!

Nested bullets are not yet supported in `rendercv>=2.0`. You can use my workaround in `rendercv<2.0`.

**Comment by amarvin** [comment]
YAML syntax is a bit tricky to allow nested lists. I found this approach (https://stackoverflow.com/a/16335038/6068036) is allowed YAML syntax:

```yml
    experience:
      - company: MyCompany
        position: MyJob
        start_date: 2024-09
        highlights:
          - Project 1
          - - Deliverable 1
            - Deliverable 2
          - Project 2
          - - Challenge 1
            - Deliverable 3
```

but then `rendercv` throws an error:

```py
There are some errors in the data model!                                                                                                                               

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Location                              ┃ Input Value ┃ Error Message                                                                                                 ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ cv.sections.experience                │             │ There are problems with the entries. RenderCV detected the entry type of this section to be ExperienceEntry!  │
│                                       │             │ The problems are shown below.                                                                                 │
├───────────────────────────────────────┼─────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ cv.sections.experience.0.highlights.1 │             │ This field should be a string!                                                                                │
├───────────────────────────────────────┼─────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ cv.sections.experience.0.highlights.3 │             │ This field should be a string!                                                                                │
└───────────────────────────────────────┴─────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "c:\Git\GitHub\resume\build.py", line 3, in <module>
    cli_command_render("resume.yaml")
  File "C:\Git\GitHub\resume\.venv\Lib\site-packages\rendercv\cli\printer.py", line 349, in wrapper
    raise typer.Exit(code)
click.exceptions.Exit: 4
```

**Comment by amarvin** [comment]
I found an alternative YAML syntax for multi-line strings that contain special characters, such as `-` (https://stackoverflow.com/a/22483116/6068036). This syntax works with `rendercv` to build a PDF with nested bullets, but the formatting is off

```yml
    experience:
      - company: MyCompany
        position: MyJob
        start_date: 2024-09
        highlights:
          - >
            Project 1
              - Deliverable 1
              - Deliverable 2
          - >
            Project 2
              - Challenge 1
              - Deliverable 3
```

![Image](https://github.com/user-attachments/assets/1fcaa990-763a-4ec6-8ec9-b92c0cdfbf82)

**Comment by mkbhuiyan96** [comment]
Seems to have worked for me. Might have to play around with some settings, e.g. `vertical_space_between_highlights` under `highlights` section

![Image](https://github.com/user-attachments/assets/01b7a3df-7d04-4e07-bd5a-421a0d5e00f3)

**Comment by amarvin** [comment]
The sub-bullets also don't take up the full width of the page. This seems to be a known bug in Typst (https://github.com/typst/typst/issues/529).

**Comment by amarvin** [comment]
> The sub-bullets also don't take up the full width of the page. This seems to be a known bug in Typst ([typst/typst#529](https://github.com/typst/typst/issues/529)).

Never mind, this isn't an issue if the sub-bullet dashes are tabbed over another two spaces. I edited my example above to match.

**Comment by amarvin** [comment]
> Seems to have worked for me. Might have to play around with some settings, e.g. `vertical_space_between_highlights` under `highlights` section
> 
> ![Image](https://github.com/user-attachments/assets/01b7a3df-7d04-4e07-bd5a-421a0d5e00f3)

Can you share a minimal example?

**Comment by mkbhuiyan96** [comment]
```yaml
design:
  theme: "sb2nov"
  entries:
    date_and_location_width: "5cm"
    left_and_right_margin: "0.05cm"
    vertical_space_between_entries: "1em"
  highlights:
    bullet: "•"
    top_margin: "0.3cm"
    left_margin: "0.1cm"
    vertical_space_between_highlights: "0.22cm"
    horizontal_space_between_bullet_and_highlight: "0.4em"
```

**Comment by amarvin** [comment]
> design:
>   theme: "sb2nov"
>   entries:
>     date_and_location_width: "5cm"
>     left_and_right_margin: "0.05cm"
>     vertical_space_between_entries: "1em"
>   highlights:
>     bullet: "•"
>     top_margin: "0.3cm"
>     left_margin: "0.1cm"
>     vertical_space_between_highlights: "0.22cm"
>     horizontal_space_between_bullet_and_highlight: "0.4em"

Hmm, it still doesn't look right to me:

![Image](https://github.com/user-attachments/assets/91c52999-fb61-4692-ae0f-56b1db4720d3)

for this minimal example:

```yml
---
cv:
  name: John Doe
  sections:
    experience:
      - company: MyCompany
        position: MyJob
        start_date: 2024-09
        highlights:
          - >
            Project 1
              - Deliverable 1
              - Deliverable 2
          - >
            Project 2
              - Challenge 1
              - Deliverable 3
design:
  theme: sb2nov
  entries:
    date_and_location_width: "5cm"
    left_and_right_margin: "0.05cm"
    vertical_space_between_entries: "1em"
  highlights:
    bullet: "•"
    top_margin: "0.3cm"
    left_margin: "0.1cm"
    vertical_space_between_highlights: "0.22cm"
    horizontal_space_between_bullet_and_highlight: "0.4em"
```

**Comment by mkbhuiyan96** [comment]
Hmm... is it something to do with the renderer? What happens once you download the PDF? It looks normal on my end.

**Comment by amarvin** [comment]
> Hmm... is it something to do with the renderer? What happens once you download the PDF? It looks normal on my end.

Oh, I was running locally from Python. You are correct that the RenderCV web app (https://app.rendercv.com/) renders this example correctly, but I'm not sure how this web app is configured.

**Comment by amarvin** [comment]
Weirdly in the RenderCV web app (https://app.rendercv.com/), even this example renders well:

```yml
cv:
  name: "John Doe"
  sections:
    experience:
      - company: "MyCompany"
        position: "MyJob"
        start_date: "2024-09"
        highlights:
          - Project 1
              - Deliverable 1
              - Deliverable 2
          - Project 2
              - Challenge 1
              - Deliverable 3
design:
  theme: "sb2nov"
  highlights:
    bullet: •
    nested_bullet: ◆
```

yet when I use Python 13.3 locally with `rendercv==2.2.0`, the same example returns an error:

```py
There are some errors in the data model!                                                                    

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Location                        ┃ Input Value ┃ Error Message                                            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ design.highlights.nested_bullet │ ◆           │ This field is unknown for this object! Please remove it. │
└─────────────────────────────────┴─────────────┴──────────────────────────────────────────────────────────┘
```

Is this new highlights attribute `nested_bullet` not fully implemented in v2.2?
