### ISSUE TITLE
Allow section title alias to maximize flexibility & compatibility with other languages

### ISSUE THREAD

**Issue by jaepil-choi** [sinaatalay/RenderCV#196]
Currently, yaml's section title is directly converted to the actual section title. 

i.e, education_and_certificates: is converted to Education and Certificates in the resume. 

However, the user might want something like: Education & Certificates, which is not something I can express as yaml's key. 

Also, it limits the compatibility with other languages in case someone wants to write the section titles in their own language like Korean, Chinese, etc. 

I suggest making an alias for each section title like: 

education_and_cert:
    - alias: "Education & Certificates" 
    - ...

that overrides yaml's raw key and use alias instead.

**Comment by sinaatalay** [comment]
Hello, actually, the section titles are totally independent strings, and there is no limit to what you can write with them.

You can use "Education & Certificates" title, as shown below.

```yaml
cv:
  sections:
    education_\&_certificates:
      - Text entry.
```
It has backslash before & it because of a bug where $\LaTeX$ characters were not escaped in section titles (#191), which is fixed now and will be released with the new version (so the key will be `education_&_certificates` instead of `education_\&_certificates`).

Also, any section title can be written like shown below:

```yaml
cv:
  sections:
    "This is my section title: and it has no limits of what can be written":
      - Text entry.
```

Languages with different characters is another issue, which is a little hard to tackle as discussed in #61 and #94.
