### ISSUE TITLE
Placeholders not supported in output_folder_name

### ISSUE THREAD

**Issue by shawnz** [sinaatalay/RenderCV#207]
**Describe the bug**
Despite the docs indicating that placeholders should be supported in the output_folder_name setting, they don't get substituted when used in that setting. See the documentation here: https://docs.rendercv.com/reference/data/models/rendercv_settings/#__codelineno-0-44

**To Reproduce**
Try executing the following YAML:

```yaml
cv:
  name: Shawn Zivontsis
  
rendercv_settings:
  render_command:
    output_folder_name: rendercv_output/NAME_IN_SNAKE_CASE_CV
```

Based on the docs, the output should be produced in the `rendercv_output/Shawn_Zivontsis_CV` directory. But actually, it will be produced in the `rendercv_output/NAME_IN_SNAKE_CASE_CV` directory.

**Screenshots**
Not applicable.
