### ISSUE TITLE
Add summary field to entries

### ISSUE THREAD

**Issue by kiyose** [sinaatalay/RenderCV#210]
Many times entries should have a summary field in addition to highlights.  

For example:
```
   projects:
      - name: Multi-User Drawing Tool
        summary:
          - The Multi-User Drawing Tool has been released to tens of users saving thousands of microseconds worth of effort.
        highlights:
          - Developed an electronic classroom where multiple users
            can simultaneously view and draw on a "chalkboard"
```

This is a field that is defined in JSONResume schema as well and seems to be the one area of mismatch.  

updated: PR #211 adds .summary to the entities and templates
