### ISSUE TITLE
Can't use arbitrary keys in `projects` field

### ISSUE THREAD

**Issue by Aithosa** [sinaatalay/RenderCV#225]
Like the example code below, I add two arbitrary keys in `projects` field, after render the file, the output files don't contain the two fields (overview, duty). The other fields stay normal.

```yaml
    projects:
      - name: Multi-User Drawing Tool
        date: '[github.com/name/repo](https://github.com/sinaatalay/rendercv)'
        overview: Developed an electronic classroom where multiple users
            can simultaneously view and draw on a "chalkboard"
            with each person's edits synchronized
        duty: Developed an electronic classroom where multiple users
            can simultaneously view and draw on a "chalkboard"
            with each person's edits synchronized
        highlights:
          - Developed an electronic classroom where multiple users
            can simultaneously view and draw on a "chalkboard"
            with each person's edits synchronized
          - 'Tools Used: C++, MFC'
```
