### ISSUE TITLE
URLs in Publication entry are not being properly escaped

### ISSUE THREAD

**Issue by JacksonKaunismaa** [sinaatalay/RenderCV#236]
**Describe the bug**
When entering in a value for the `url` field in a Publication entry, if you input a link containing an underscore, rendering the PDF will fail, as the underscore will not be escaped. When manual escaping is attempted, as in #223 , backslashes are automatically converted to forward slashes, so the escaping doesn't work.

**To Reproduce**

```yaml
publications:
    - title: Paper name
      authors: 
          - Me
      url: https://link.com/link_with_underscore
      date: Dec 2024
```

TeX output for url:

`\href{https://link.com/link_with_underscore}{link.com/link_with_underscore}`

If we try to escape:

```yaml
publications:
    - title: Paper name
      authors: 
          - Me
      url: https://link.com/link\_with\_underscore
      date: Dec 2024
```

TeX output for url:

`\href{https://link.com/link/_with/_underscore}{link.com/link/_with/_underscore}`

Both cases fail to render into a pdf.
