### ISSUE TITLE
Ability to add markdown formatting to the authors in publications

### ISSUE THREAD

**Issue by lhegstrom** [sinaatalay/RenderCV#27]
First - this is a fantastic project! Super useful.

In the academic space it's common to have a list of dozens of papers / abstracts / posters, etc. Being able to apply formatting to the authors list - like either bolding, or italicizing (or both) would help. Similar to how this guy's name is highlighted as a part of his research: 
<img width="765" alt="Screenshot 2024-03-03 at 19 54 58" src="https://github.com/sinaatalay/rendercv/assets/98775726/df5cd6b2-2afc-4e53-ad89-62425067e07c">

**Comment by sinaatalay** [comment]
This is a very good idea!

Currently, RenderCV automatically makes the CV owner’s name bold and italic in the authors list. However, I think removing that feature and allowing the users to do whatever they want with Markdown sounds more elegant and flexible.

Also, it made me think about another thing: RenderCV currently writes authors' first names with their initials. That can also be removed, and then users can decide if they want to use initials or not.

I will implement these in the next release.

**Comment by lhegstrom** [comment]
Huh, interesting - it doesn't render as bold on my Mac when using the classic theme. I see now on the example PDF there's bolding. I'd bet there's an OS PDF creation difference somewhere. Getting a consistent output across Mac/Unix/Windows is ... challenging.

EDIT - it's due to adding degrees to the name. Adding a MD/JD/PhD/MS/etc behind the name but not in the publications causes the bolding to be skipped

**Comment by sinaatalay** [comment]
Okay then, when we switch to pure Markdown, that issue will also go away.

**Comment by anibaltafur** [comment]
I was having a somewhat similar issue/requirement. As a work around I'm using the `Normal Entry` format, and I can format author names and journal titles using Markdown (example below).
It would be nice if in the future there could be another entry type with simple bulleted items, in this way I could potentially couple your package with some scripts I have to manipulate references. The `Text Entry` one does not have bullets in the `classic` theme 😢 , and the `Normal Entry` requires name, otherwise, renders an empty line. 

By the way, nice package, thanks!! @sinaatalay 

```yaml
academic_work:
      - name: Journal papers
        highlights:
        - 'Hain A., Zaghi A.E., Padgett J.E., **Tafur A.** (2023). Case studies of multihazard damage:
          Investigation of the interaction of Hurricane Maria and the January 2020 earthquake sequence in
          Puerto Rico. *Frontiers in Built Environment.* 
          DOI: [10.3389/fbuil.2023.1128573](https://doi.org/10.3389/fbuil.2023.1128573)'
        - 'Paper 2'
      - name: Conference papers
        highlights:
        - 'Paper 1'
        - 'Paper 2' 
```

<img width="512" alt="image" src="https://github.com/sinaatalay/rendercv/assets/54555240/81a176c4-25a8-44fe-adf3-a561c0d3ab3e">
