### ISSUE TITLE
new bold_keywords setting doesn't work with multiple keywords

### ISSUE THREAD

**Issue by benjuntilla** [sinaatalay/RenderCV#286]
Rendering a YAML specifying keywords under `rendercv_settings.bold_keywords` should surround occurrences of those keywords with double asterisks, bolding those keywords in the result PDF. But, using v1.18 of the CLI, specifying two or more keywords to bold will result in unexpected behavior.

## To reproduce
Render the following YAML with `rendercv render debug.yaml -use pdflatex`

```yaml
cv:
  name: Ben Juntilla
  sections:
    experience:
      - company: Circle K
        position: Snack Eater
        highlights:
          - bananas apples pears

design:
  theme: engineeringresumes
  font: Source Sans 3

rendercv_settings:
  bold_keywords:
    - bananas
    - apples
    - pears
```

## Screenshots
**Bolding one keyword:**
```yaml
    - bananas
    # - apples
    # - pears
```
![image](https://github.com/user-attachments/assets/97dc94f0-56de-4bd5-b27e-06dcb46ace3b)
(Works!)

**Bolding two keywords:**
```yaml
    - bananas
    - apples
    # - pears
```
![image](https://github.com/user-attachments/assets/0bbfc0db-b1a4-4674-a853-09b1fccac592)
(Not so much)

**Bolding three keywords:**
```yaml
    - bananas
    - apples
    - pears
```
![image](https://github.com/user-attachments/assets/d9c5ed0e-1aca-481a-8511-d66689d7d858)
(Not at all)

**Bolding four keywords (also added an additional word in the highlights):**
```yaml
    - bananas
    - apples
    - pears
    - oranges
```
![image](https://github.com/user-attachments/assets/b655f0df-589c-4e90-a7b6-a1a95053df80)

## Possible root cause
I think it's because `make_given_keywords_bold_in_a_dictionary` in `utilities.py` creates a shallow copy with `dictionary.copy()`, resulting in shared references between the new and old dictionaries. I already have a fix that works on my end, so I'll open a PR soon.
