### ISSUE TITLE
Asterisk needs translation in 2.0

### ISSUE THREAD

**Issue by lczyk** [sinaatalay/RenderCV#293]
```yaml
education:
    - institution: Some College
      area: ""
      degree: A-Levels
      highlights:
          - 1A* in Computer Science
```

causes:

```
error: unclosed delimiter
    ┌─ rendercv_output/Jon_Doe_CV.typ:474:52
    │
474 │     #v(design-highlights-top-margin);#highlights([1A* in Computer Science],)
    │                                                     ^

```

Maybe translating to `#highlights([1A#ast.basic in Computer Science],)` ?
