### ISSUE TITLE
Generate invalid typst source for multiline titles in 2.0

### ISSUE THREAD

**Issue by lczyk** [sinaatalay/RenderCV#294]
```yaml
publications:
    - title: Short title
        authors:
            - Jon Doe
        doi: 10.1234/ABCDEF567G
        date: 2000-01-01
        journal: Nature
    - title: |
            Very long title which is so long that it needs to be split
            over multiple lines
        authors:
            - Paul Smith
        doi: 10.9876/XYZ123456A
        date: 2000-02-02
        journal: Nurture
```

causes:

```
error: unclosed delimiter
    ┌─ rendercv_output/Jon_Doe_CV.typ:569:6
    │
569 │     #[*Very long title which is so long that it needs to be split
    │       ^

error: unclosed delimiter
    ┌─ rendercv_output/Jon_Doe_CV.typ:573:0
    │
573 │ *]
    │ ^
```

Examining the .typ source shows the problem clearly:

```typst
#two-col-entry(
  left-content: [
    #[*Short title*]

  ],
  right-content: [
    Jan 2000
  ],
)
#one-col-entry(content:[
#v(design-highlights-top-margin);Jon Doe

#v(design-highlights-top-margin - design-text-leading)#link("https://doi.org/10.1234/ABCDEF567G")[10.1234/ABCDEF567G] (Nature)])

#v(design-entries-vertical-space-between-entries)
#two-col-entry(
  left-content: [
    #[*Very long title which is so long that it needs to be split

over multiple lines

*]

  ],
  right-content: [
    Feb 2000
  ],
)
#one-col-entry(content:[
#v(design-highlights-top-margin);Paul Smith

#v(design-highlights-top-margin - design-text-leading)#link("https://doi.org/10.9876/XYZ123456A")[10.9876/XYZ123456A] (Nurture)])
```

I'd suggest preprocessing yaml to (1) remove the newlines for newline entries (is there ever a case where that's not desired?) as well as (2) use [`#strong`](https://typst.app/docs/reference/model/strong/) as as opposed to `*` since `[]`'s split over multiple lines -- not only in the above case but whenever rendercv wants to make something bold.
