### ISSUE TITLE
Icons are not appearing instead showing ? enclosed in a box in the pdf

### ISSUE THREAD

**Issue by susmigo1210** [sinaatalay/RenderCV#295]
location: Your Location
  email: youremail@yourdomain.com
  phone: +905-419999999
  website: https://yourwebsite.com/
  social_networks:
    - network: LinkedIn
      username: yourusername
    - network: GitHub
      username: yourusername

<img width="767" alt="Screenshot 2025-01-08 at 07 46 52" src="https://github.com/user-attachments/assets/3d73e4e6-e746-49a5-bc54-8f7f205ebe5c" />

**Comment by susmigo1210** [comment]
pasting here the design and rendercv settings

```
design:
  theme: classic
  page:
    size: us-letter
    top_margin: 2cm
    bottom_margin: 2cm
    left_margin: 2cm
    right_margin: 2cm
    show_page_numbering: true
    show_last_updated_date: true
  colors:
    text: black
    name: "#004f90"
    connections: "#004f90"
    section_titles: "#004f90"
    links: "#004f90"
    last_updated_date_and_page_numbering: grey
  text:
    font_family: Source Sans 3
    font_size: 10pt
    leading: 0.6em
    alignment: justified
    date_and_location_column_alignment: right
  links:
    underline: false
    use_external_link_icon: false
  header:
    name_font_size: 30pt
    name_bold: true
    photo_width: 3.5cm
    vertical_space_between_name_and_connections: 0.7cm
    vertical_space_between_connections_and_first_section: 0.7cm
    horizontal_space_between_connections: 0.5cm
    separator_between_connections: "|"
    use_icons_for_connections: true
    alignment: center
  section_titles:
    type: with-parial-line
    font_size: 1.4em
    bold: true
    small_caps: false
    line_thickness: 0.5pt
    vertical_space_above: 0.5cm
    vertical_space_below: 0.3cm
  entries:
    date_and_location_width: 4.15cm
    left_and_right_margin: 0.2cm
    horizontal_space_between_columns: 0.1cm
    vertical_space_between_entries: 1.2em
    allow_page_break_in_entries: true
    short_second_row: false
    show_time_spans_in: []
  highlights:
    bullet: •
    top_margin: 0.25cm
    left_margin: 0.4cm
    vertical_space_between_highlights: 0.25cm
    horizontal_space_between_bullet_and_highlight: 0.5em
    summary_left_margin: 0cm
  entry_types:
    one_line_entry:
      template: "**LABEL:** DETAILS"
    education_entry:
      main_column_first_row_template: "**INSTITUTION**, AREA"
      degree_column_template: "**DEGREE**"
      degree_column_width: 1cm
      main_column_second_row_template: "SUMMARY\nHIGHLIGHTS"
      date_and_location_column_template: "LOCATION\nDATE"
    normal_entry:
      main_column_first_row_template: "**NAME**"
      main_column_second_row_template: "SUMMARY\nHIGHLIGHTS"
      date_and_location_column_template: "LOCATION\nDATE"
    experience_entry:
      main_column_first_row_template: "**COMPANY**, POSITION"
      main_column_second_row_template: "SUMMARY\nHIGHLIGHTS"
      date_and_location_column_template: "LOCATION\nDATE"
    publication_entry:
      main_column_first_row_template: "**TITLE**"
      main_column_second_row_template: "AUTHORS\nURL (JOURNAL)"
      main_column_second_row_without_journal_template: "AUTHORS\n\
        URL"
      main_column_second_row_without_url_template: "AUTHORS\n\
        JOURNAL"
      date_and_location_column_template: DATE
locale:
  language: en
  phone_number_format: national
  page_numbering_template: NAME - Page PAGE_NUMBER of TOTAL_PAGES
  last_updated_date_template: Last updated in TODAY
  date_template: MONTH_ABBREVIATION YEAR
  month: month
  months: months
  year: year
  years: years
  present: present
  to: –
  abbreviations_for_months:
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - June
    - July
    - Aug
    - Sept
    - Oct
    - Nov
    - Dec
  full_names_of_months:
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
rendercv_settings:
  date: "2025-01-08"
  render_command:
    output_folder_name: resume
  bold_keywords: []

```
