### ISSUE TITLE
Examples of using complex arbitrary keys with `design.entry_types`

### ISSUE THREAD

**Issue by nusnewob** [sinaatalay/RenderCV#334]
The documentation did mention this: https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#using-arbitrary-keys

However there's no example of how to use `design.entry_types` field. and if I'd like to use a slightly more complex structure in an arbitrary key, is it even possible, such as,

```yaml
cv:
  sections:
    experience:
      - company: some_company
         position: project manager
         projects:
           - name: project_a
              summary: did something
              highlights:
                - did this
                - did that
           - name: project_b
              summary: built something
              highlights:
                - built this
                - built that
```
