### ISSUE TITLE
Position Text Overlaps with Company Name in Experience Section Display

### ISSUE THREAD

**Issue by amaanansari** [sinaatalay/RenderCV#357]
**Describe the bug**
When position is set to be displayed beneath the company name via the design, the position text is overlapping with the company name (see screenshot)

**To Reproduce**
Please provide a minimal YAML input as a code block for us to produce the same error.
rendercv==2.2

in cv:
```
      - company: Testcompany
        position: "Testposition"
        date:
        start_date: 2024-06
        end_date: present
        location: Testlocation
        summary: Testsummary – that is - very long
```

in design:
```
     experience_entry:
      main_column_first_row_template: '**COMPANY**'
      main_column_second_row_template: |-
        POSITION 
        SUMMARY
        HIGHLIGHTS
```

**Screenshots**
Visualization of the bug:

![Image](https://github.com/user-attachments/assets/a7af7b6f-b576-4a3d-b6af-2731f4c249e7)
