### ISSUE TITLE
create_a_pdf_from_a_python_dictionary function not creating a pdf file

### ISSUE THREAD

**Issue by NeodarZ** [sinaatalay/RenderCV#358]
**Describe the bug**

I did try to use `rendercv` directly as a module, I simply wanted to use the function `create_a_pdf_from_a_python_dictionary` as the docstring sayed `generate a PDF file` I was expecting a PDF file in the generated file but I get... a typst instead...

Based on the name of the function and the description I would have expected to have a PDF file.

After a check in the  [code](https://github.com/rendercv/rendercv/blob/main/rendercv/api/functions.py#L376C27-L376C32) there is the same behavior with the function `create_a_pdf_from_a_yaml_string` as they both use `create_a_typst_file` instead of `create_a_pdf_file` (doesn't exist) as I would have expected to read.

**To Reproduce**

The yaml file used:

```yaml
cv:
  name: John Doe
  location: Location
  email: john.doe@example.com
  phone: +1-609-999-9995
  website:
  social_networks:
    - network: LinkedIn
      username: john.doe
    - network: GitHub
      username: john.doe
  sections:
    welcome_to_RenderCV!:
      - '[RenderCV](https://rendercv.com) is a Typst-based CV framework designed for academics and engineers, with Markdown syntax support.'
      - Each section title is arbitrary. Each section contains a list of entries, and there are 7 different entry types to choose from.
    education:
      - institution: Stanford University
        area: Computer Science
        degree: PhD
        date:
        start_date: 2023-09
        end_date: present
        location: Stanford, CA, USA
        summary:
        highlights:
          - Working on the optimization of autonomous vehicles in urban environments
      - institution: Boğaziçi University
        area: Computer Engineering
        degree: BS
        date:
        start_date: 2018-09
        end_date: 2022-06
        location: Istanbul, Türkiye
        summary:
        highlights:
          - 'GPA: 3.9/4.0, ranked 1st out of 100 students'
          - 'Awards: Best Senior Project, High Honor'
    experience:
      - company: Company C
        position: Summer Intern
        date:
        start_date: 2024-06
        end_date: 2024-09
        location: Livingston, LA, USA
        summary:
        highlights:
          - Developed deep learning models for the detection of gravitational waves in LIGO data
          - Published [3 peer-reviewed research papers](https://example.com) about the project and results
      - company: Company B
        position: Summer Intern
        date:
        start_date: 2023-06
        end_date: 2023-09
        location: Ankara, Türkiye
        summary:
        highlights:
          - Optimized the production line by 15% by implementing a new scheduling algorithm
      - company: Company A
        position: Summer Intern
        date:
        start_date: 2022-06
        end_date: 2022-09
        location: Istanbul, Türkiye
        summary:
        highlights:
          - Designed an inventory management web application for a warehouse
    projects:
      - name: '[Example Project](https://example.com)'
        date:
        start_date: 2024-05
        end_date: present
        location:
        summary: A web application for writing essays
        highlights:
          - Launched an [iOS app](https://example.com) in 09/2024 that currently has 10k+ monthly active users
          - The app is made open-source (3,000+ stars [on GitHub](https://github.com))
      - name: '[Teaching on Udemy](https://example.com)'
        date: Fall 2023
        start_date:
        end_date:
        location:
        summary:
        highlights:
          - Instructed the "Statics" course on Udemy (60,000+ students, 200,000+ hours watched)
    skills:
      - label: Programming
        details: Proficient with Python, C++, and Git; good understanding of Web, app development, and DevOps
      - label: Mathematics
        details: Good understanding of differential equations, calculus, and linear algebra
      - label: Languages
        details: 'English (fluent, TOEFL: 118/120), Turkish (native)'
    publications:
      - title: 3D Finite Element Analysis of No-Insulation Coils
        authors:
          - Frodo Baggins
          - '***John Doe***'
          - Samwise Gamgee
        doi: 10.1109/TASC.2023.3340648
        url:
        journal:
        date: 2004-01
    extracurricular_activities:
      - bullet: 'There are 7 unique entry types in RenderCV: *BulletEntry*, *TextEntry*, *EducationEntry*, *ExperienceEntry*, *NormalEntry*, *PublicationEntry*, and *OneLineEntry*.'
      - bullet: Each entry type has a different structure and layout. This document demonstrates all of them.
    numbered_entries:
      - number: This is a numbered entry.
      - number: This is another numbered entry.
      - number: This is the third numbered entry.
    reversed_numbered_entries:
      - reversed_number: This is a reversed numbered entry.
      - reversed_number: This is another reversed numbered entry.
      - reversed_number: This is the third reversed numbered entry.
design:
  theme: classic
  page:
    size: us-letter
    top_margin: 2cm
    bottom_margin: 2cm
    left_margin: 2cm
    right_margin: 2cm
    show_page_numbering: true
    show_last_updated_date: true
  colors:
    text: rgb(0, 0, 0)
    name: rgb(0, 79, 144)
    connections: rgb(0, 79, 144)
    section_titles: rgb(0, 79, 144)
    links: rgb(0, 79, 144)
    last_updated_date_and_page_numbering: rgb(128, 128, 128)
  text:
    font_family: Source Sans 3
    font_size: 10pt
    leading: 0.6em
    alignment: justified
    date_and_location_column_alignment: right
  links:
    underline: false
    use_external_link_icon: true
  header:
    name_font_family: Source Sans 3
    name_font_size: 30pt
    name_bold: true
    photo_width: 3.5cm
    vertical_space_between_name_and_connections: 0.7cm
    vertical_space_between_connections_and_first_section: 0.7cm
    horizontal_space_between_connections: 0.5cm
    connections_font_family: Source Sans 3
    separator_between_connections: ''
    use_icons_for_connections: true
    alignment: center
  section_titles:
    type: with-parial-line
    font_family: Source Sans 3
    font_size: 1.4em
    bold: true
    small_caps: false
    line_thickness: 0.5pt
    vertical_space_above: 0.5cm
    vertical_space_below: 0.3cm
  entries:
    date_and_location_width: 4.15cm
    left_and_right_margin: 0.2cm
    horizontal_space_between_columns: 0.1cm
    vertical_space_between_entries: 1.2em
    allow_page_break_in_sections: true
    allow_page_break_in_entries: true
    short_second_row: false
    show_time_spans_in: []
  highlights:
    bullet: •
    top_margin: 0.25cm
    left_margin: 0.4cm
    vertical_space_between_highlights: 0.25cm
    horizontal_space_between_bullet_and_highlight: 0.5em
    summary_left_margin: 0cm
  entry_types:
    one_line_entry:
      template: '**LABEL:** DETAILS'
    education_entry:
      main_column_first_row_template: '**INSTITUTION**, AREA'
      degree_column_template: '**DEGREE**'
      degree_column_width: 1cm
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    normal_entry:
      main_column_first_row_template: '**NAME**'
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    experience_entry:
      main_column_first_row_template: '**COMPANY**, POSITION'
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    publication_entry:
      main_column_first_row_template: '**TITLE**'
      main_column_second_row_template: |-
        AUTHORS
        URL (JOURNAL)
      main_column_second_row_without_journal_template: |-
        AUTHORS
        URL
      main_column_second_row_without_url_template: |-
        AUTHORS
        JOURNAL
      date_and_location_column_template: DATE
locale:
  language: en
  phone_number_format: national
  page_numbering_template: NAME - Page PAGE_NUMBER of TOTAL_PAGES
  last_updated_date_template: Last updated in TODAY
  date_template: MONTH_ABBREVIATION YEAR
  month: month
  months: months
  year: year
  years: years
  present: present
  to: –
  abbreviations_for_months:
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - June
    - July
    - Aug
    - Sept
    - Oct
    - Nov
    - Dec
  full_names_of_months:
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
rendercv_settings:
  date: '2025-02-02'
  render_command:
  bold_keywords: []
```

Python test code:

```python
import yaml

CV_name = "John_Doe_ClassicTheme_CV"

with open(f"{CV_name}.yaml", "r") as John_Doe_ClassicTheme_CV:
    cv_data = yaml.safe_load(John_Doe_ClassicTheme_CV)

from rendercv.api import create_a_pdf_from_a_python_dictionary

create_a_pdf_from_a_python_dictionary(
    cv_data,
    f"{CV_name}.pdf"
)

with open(f"{CV_name}.pdf", "r") as John_Doe_ClassicTheme_CV_pdf:
    cv_pdf = John_Doe_ClassicTheme_CV_pdf.read()

print(cv_pdf[:40])
```

This python script will print something like:

```console

#import "@preview/fontawesome:0.5.0": f
```

**Details**

And if you try to open the pdf generated:

![Image](https://github.com/user-attachments/assets/2f86febe-d309-448a-a9b0-24744a7acc8a)
