### ISSUE TITLE
Add Reference Entry type

### ISSUE THREAD

**Issue by elaske** [sinaatalay/RenderCV#368]
This doesn't seem to fit into any other format. If you would like to add references, see some of the formats listed here:
* https://www.indeed.com/career-advice/resumes-cover-letters/resume-reference-list
* https://www.jobscan.co/blog/references-on-a-resume/

This can sort of be shoe-horned in by using a normal entry or one-line entry, but I would think that it would be useful to have formats that accommodate telephone numbers, email addresses, etc. within them. The only thing that does that now is the header.

Things that would be important:
* Name
* Title / Role (optional)
* Company (optional)
* Telephone (optional)
* Email (optional)
* Label / Summary (optional) - to add flavor / detail of what they can speak to
* Dates - start / end (optional) - "from [start date]" or "[start-date - end-date]" or None

**Comment by sinaatalay** [comment]
Could you please illustrate on a PDF how this entry type should appear, or provide a specific image from the links? The reason I am asking is: https://docs.rendercv.com/developer_guide/faq/#when-should-we-consider-adding-a-new-entry-type-to-rendercv

**Comment by elaske** [comment]
Example from the second link looks like: 

![Image](https://github.com/user-attachments/assets/a11a7cd3-58ec-4ce6-bd2c-4033f71d92a7)

I think that depending on the template you might want to have a more condensed version of this, e.g.,

NAME, ROLE, COMPANY | DATE
SUMMARY
PHONE EMAIL (formatted same way as header)

**Comment by sinaatalay** [comment]
This can be done with TextEntry. Does this meet your requirements?

```yaml
cv:
  sections:
    references:
      - |
        **BOLD NAME**
      
        Company

        Anything else

        Email: [dev@example.com](mailto:dev@example.com)

        **Note:** *Italic note*
```
