### ISSUE TITLE
DOCS: Usage of arbitrary keys in templates

### ISSUE THREAD

**Issue by sinaatalay** [sinaatalay/RenderCV#376]
### Discussed in https://github.com/rendercv/rendercv/discussions/375

<div type='discussions-op-text'>

<sup>Originally posted by **dfego** March 14, 2025</sup>
I've been reviewing the documentation and discussions here, and I've yet to find an actual _explanation_ as to how arbitrary keys are supposed to work. All I've found is [Using arbitrary keys](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#using-arbitrary-keys), which says:

> By default, the an_arbitrary_key key will not affect the output as the default design options do not use it. However, you can use the an_arbitrary_key key in your own design options (see design.entry_types field).

So I look down at `design.entry_types` and there's no actual explanation of what to do. I think I've discovered the following through trial and error:

1. Lowercase keys are represented by all-caps in the templates
2. Using text in templates that is _not_ a key results in the literal text appearing
3. Using a key in _any_ entry makes it recognized as a key seemingly for any template

However, when I use my key (let's say `arbitrary`) in my entry_types, by putting the text `ARBITRARY`, it doesn't show up. It clearly is recognized as a key because of number 2 above not occurring.

Is there more documentation and examples around this that I haven't found, or does it not exist? I'm also looking for documentation on the `.j2.typ` files.</div>

**Comment by sinaatalay** [comment]
See https://github.com/rendercv/rendercv/discussions/375#discussioncomment-12504548

**Comment by AlexColello** [comment]
I also ran into a lot of trouble using custom attributes and eventually found what I think is a bug that makes the behavior unintuitive. The custom fields in the yaml must be fully capitalized to work correctly, otherwise they will be filled in with an empty string. An example of a working yaml would be:
```
cv:
  name: Example
  location: Location
  email: john.doe@example.com
  phone: +1-609-999-9995
  website:
  social_networks:
    - network: LinkedIn
      username: john.doe
    - network: GitHub
      username: john.doe
  sections:
    experience:
      - company: Company A
        position: Summer Intern
        ARBITRARY: Monkeys
...
    experience_entry:
      main_column_first_row_template: "**COMPANY**, POSITION, ARBITRARY, POSITION"
...
```
I was able to get it to accept lower case by changing https://github.com/rendercv/rendercv/blob/main/rendercv/renderer/templater.py#L194 to use `lowercase_placeholder_key` rather than `placeholder_key`, however that doesn't account for people wanting to put capital letters in their arbitrary key.
