### ISSUE TITLE
section_titles with-partial-line not rendering

### ISSUE THREAD

**Issue by NeodarZ** [sinaatalay/RenderCV#379]
**Describe the bug**

While the typo is fixed the partial line is not rendered anymore for some reason.

**Warning** This is the code on master at the time I am writing this issue, sorry in advance if this was a bad idea, I am just thinking this is still a good idea to report.

**To Reproduce**

```
cv:
  name: John Doe
  location: Somewhere
  email: test@example.com
  phone: "+1 206 555 0100"
  sections:
    about:
      - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    experience:
      - company: Lorem ipsum dolor sit amet
        position: commodo consequat
        start_date: 1320
        end_date: 1490
        location: Here, Hearth
        highlights:
          - Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
          - Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
          - Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.

design:
  theme: engineeringresumes
  page:
    size: us-letter
    top_margin: 2cm
    bottom_margin: 2cm
    left_margin: 2cm
    right_margin: 2cm
    show_page_numbering: false
    show_last_updated_date: false
  colors:
    text: rgb(0, 0, 0)
    name: rgb(0, 0, 0)
    connections: rgb(0, 0, 0)
    section_titles: rgb(0, 0, 0)
    links: rgb(0, 0, 0)
    last_updated_date_and_page_numbering: rgb(128, 128, 128)
  text:
    font_family: XCharter
    font_size: 10pt
    leading: 0.6em
    alignment: justified
    date_and_location_column_alignment: right
  links:
    underline: true
    use_external_link_icon: false
  header:
    name_font_family: XCharter
    name_font_size: 25pt
    name_bold: false
    photo_width: 3.5cm
    vertical_space_between_name_and_connections: 0.7cm
    vertical_space_between_connections_and_first_section: 0.7cm
    horizontal_space_between_connections: 0.5cm
    connections_font_family: XCharter
    separator_between_connections: '|'
    use_icons_for_connections: false
    alignment: center
  section_titles:
    type: with-partial-line
    font_family: XCharter
    font_size: 1.2em
    bold: true
    small_caps: false
    line_thickness: 0.5pt
    vertical_space_above: 0.55cm
    vertical_space_below: 0.3cm
  entries:
    date_and_location_width: 4.15cm
    left_and_right_margin: 0cm
    horizontal_space_between_columns: 0.1cm
    vertical_space_between_entries: 0.4cm
    allow_page_break_in_sections: true
    allow_page_break_in_entries: true
    short_second_row: false
    show_time_spans_in: []
  highlights:
    bullet: •
    top_margin: 0.25cm
    left_margin: 0cm
    vertical_space_between_highlights: 0.19cm
    horizontal_space_between_bullet_and_highlight: 0.3em
    summary_left_margin: 0cm
  entry_types:
    one_line_entry:
      template: '**LABEL:** DETAILS'
    education_entry:
      main_column_first_row_template: '**INSTITUTION**, DEGREE in AREA -- LOCATION'
      degree_column_template:
      degree_column_width: 1cm
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    normal_entry:
      main_column_first_row_template: '**NAME** -- **LOCATION**'
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    experience_entry:
      main_column_first_row_template: '**POSITION**, COMPANY -- LOCATION'
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    publication_entry:
      main_column_first_row_template: '**TITLE**'
      main_column_second_row_template: |-
        AUTHORS
        URL (JOURNAL)
      main_column_second_row_without_journal_template: |-
        AUTHORS
        URL
      main_column_second_row_without_url_template: |-
        AUTHORS
        JOURNAL
      date_and_location_column_template: DATE
locale:
  language: en
  phone_number_format: national
  page_numbering_template: NAME - Page PAGE_NUMBER of TOTAL_PAGES
  last_updated_date_template: Last updated in TODAY
  date_template: MONTH_ABBREVIATION YEAR
  month: month
  months: months
  year: year
  years: years
  present: present
  to: –
  abbreviations_for_months:
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - June
    - July
    - Aug
    - Sept
    - Oct
    - Nov
    - Dec
  full_names_of_months:
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
rendercv_settings:
  date: '2025-02-16'
  render_command:
  bold_keywords: []

```

**Screenshots**

What I have with the version **on master**

![Image](https://github.com/user-attachments/assets/a4fc8523-789d-4ed2-b5b6-164b56113157)

What I have wit the version **2.2** and what I am expecting to see

![Image](https://github.com/user-attachments/assets/8a1c9cb6-2ff7-4502-8360-2379c6ef11f7)
