### ISSUE TITLE
Allow {start|end}_date to be less precise than a specific day

### ISSUE THREAD

**Issue by jpgoldberg** [sinaatalay/RenderCV#4]
I would like to specify start and end dates in terms of months. For example

```
 education:
    - institution: University of California, Santa Cruz
        url: https://ucsc.edu
        area: Linguistics
        study_type: BA
        location: Santa Cruz, Calinfornia, USA
        start_date: "1979-09"
        end_date: "1984-06"
```

As you might imagine, I am disinclined to dig through 40 year old records to determine the precise day of the month for those events, and anyone reading the CV isn't going to care. 

**Describe the solution you'd like**
`start_date` and `end_date` should allow YYYY-MM and YYYY forms of RFC3339 dates. 

**Additional context**

I suspect that "1979-09" is a valid RFC3339 date, in which case my feature request may be considered a bug report. 

I haven't looked at the source code (yet) to see if I can produce a useful pull request.
