### ISSUE TITLE
References entry 

### ISSUE THREAD

**Issue by ferdavs** [sinaatalay/RenderCV#42]
References entries with name, position, email, etc.
Maybe two types academic and professional like below

```yml
  references:
      - name: 
        title: Prof. Dr.
        institution: University
        email: 
     - name: 
       position: Simulation Engineer
       institution: Max Planck
       email:
```

**Comment by ferdavs** [comment]
Also 
```yaml
references: Available upon request
```

**Comment by sinaatalay** [comment]
Thank you for opening an issue!

RenderCV's entry types are not data-oriented but rendering-oriented. Unless we require a new rendering type, we wouldn't want to create a new entry type.

I will give you some suggestions about how you can achieve what you would like.

- ```yaml
  references:
    - Available upon request. # This is a TextEntry
  ```
 - ```yaml
    references:
      - bullet: "**Dr. John Doe**, *Bogazici University*, [john@doe.com](mailto:john@doe.com)" # This is a BulletEntry
      - bullet: "**Dr. John Doe**, *Bogazici University*, [john@doe.com](mailto:john@doe.com)"
      - bullet: "**Dr. John Doe**, *Bogazici University*, [john@doe.com](mailto:john@doe.com)"
    ```
  
You could also use other entry types. Whichever suits you the best. Please have a look at [the user guide](https://sinaatalay.github.io/rendercv/user_guide/).
