### ISSUE TITLE
ATS

### ISSUE THREAD

**Issue by e-hossam96** [sinaatalay/RenderCV#425]
**Describe the bug**
CV is not ATS-friendly

**To Reproduce**
```yaml
cv:
  name: Hossam Gamal Mostafa
  location: New Cairo, Cairo, Egypt
  email: example@mailcom
  phone: +20-**********
  website:
  social_networks:
    - network: LinkedIn
      username: e-hossam96
    - network: GitHub
      username: e-hossam96
  sections:
    education:
      - institution: Alexandria University
        area: Nuclear Engineering
        degree: B.Sc.
        start_date: 2015-09
        end_date: 2019-07
        location: Alexandria, Egypt
        highlights:
          - "Grade: 80% (Very Good), ranked 3rd in class."
          - "Relevant Coursework: Advanced Calculus, Linear Algebra, Differential Equations, Partial Differential Equations, Numerical Methods, Probability, Statistics, and Computer Programming with Fortran."
    experience:
      - company: Udacity
        position: Session Lead
        start_date: 2022-09
        end_date: present
        location: Remote
        highlights:
          - Delivered weekly Connect sessions in DECI (Digital Egypt Cubs Initiative) Program on elementary programming with Python, Web Development, Data Analysis, AI, Cybersecurity, Digital Arts, Electric Circuits, Embedded Systems, and Computer Architecture.
          - Mentored and monitored students' progress during sessions and office hours, ensuring standard knowledge benchmark.
          - Achieved 4.6 average mentor ratings, and 82% average graduation rates in last two cohorts.
      - company: ASAP Systems
        position: AI Developer
        start_date: 2025-01
        end_date: 2025-05
        location: Cairo, Egypt
        highlights:
          - Developed AI Forecasting solution to predict quantities and costs of various stocks of BarCloud customers. Models include zero-shot forecasting model fine-tuned on in-house databases packed with Facebook Prophet model to handle new and old customers. Enhanced solution to be accessed from forecasting dashboard and BarCloud Chat Interface served using LLM Tool Calls.
          - Designed AI Text to SQL solution to query BarCloud databases based on users' questions. Solution is intended to provide correct, accurate, and safe MS SQL queries and provide results to the users in a summarized form.
          - Worked on enhancing AI RAG solutions to answer questions about BarCloud features. Enhancements include LLM serving tools (LlamaCpp, vLLM, Ollama) and intent classification models to direct customers to different navigation pages and sections based on voice commands.
      - company: iSemantics
        position: NLP Data Scientist
        start_date: 2022-07
        end_date: 2024-09
        location: Cairo, Egypt
        highlights:
          - Contributed to research and implementation of various AI solutions, including Information Retrieval (Multilingual Named Entity Recognition (NER), Relation Extraction) and Social Sciences (Sentiment and Aspect-Based Sentiment Analysis (ABSA), Propaganda Detection, Offensive Language Identification (OLI)) achieving boosted performance of at least 20% F1 and Precision scores over strong baselines.
          - Led interviews and discussions with potential and ongoing tech and non-tech clients on integrating AI into business solutions. Successfully convinced 3 of Company's clients.
          - Researched and validated emerging Machine Learning and Generative AI concepts and papers through code implementation and statistical analysis on various datasets.
          - Developed training and learning plans aligned with Company's needs for incoming and current junior AI developers.
          - Participated in interviewing and evaluating potential interns, ensuring alignment with Company's technical requirements and cultural values. Successfully conducted 6 interviews.
          - Represented Company at Techne Summit Cairo 2024 Event.
      - company: BUE
        position: Teaching Assistant of Mathematics
        start_date: 2021-10
        end_date: 2022-09
        location: Cairo, Egypt
        highlights:
          - Delivered tutorials in various undergraduate courses, including Probability, Statistics, Numerical Methods, Differential Equations, and Calculus.
          - Assisted course professors with course logistics, including reporting student attendance, exam marking, and archiving courses on University's cloud system.
          - Achieved 4.63 out of 5 average satisfaction score based on students feedback.
    projects:
      - name: RAGBOT
        location: OSS
        # summary: Generic RAG Application Template with Databases Integrations and LLM-Guided Evaluations
        highlights:
          - Developed generic Retrieval-Augmented Generation (RAG) Application Template with Databases Integrations and Large Language Model (LLM) Guided Evaluations, utilizing Models-Controllers-Views (MCV) design pattern, offering flexibility in integrating various LLMs and vector databases.
          - Implemented 7 backend routes for data storage, data processing, document indexing, document retrieval, chat response generation, and LLM-guided evaluation.
          - Enabled document and processed text storage to ensure data persistence and eliminate need for repeated uploads and text preprocessing.
          - Allowed switching between web scrapping tools to adhere to content scraping policies of different websites (currently supporting Wikipedia API and Beautiful Soup).
          - Utilized Pydantic schema for controlled database in-out operations (embedding vector and document models).
          - Integrated flexible LLM and vector databases switching to adapt to evolving business requirements.
          - Added LLM-guided evaluation module to evaluate correctness, factfulness, and completeness of LLM responses and to control hallucination.
          - Built extendable and scalable backend to accommodate future updates and growth.
      - name: Forecasting & Inventory Optimization Solution
        location: ASAP Systems'
        # summary: AI Forecasting Pipeline for Demand and Stock Level Predictions
        highlights:
          - Developed robust forecasting engines using fine-tuned Lag-Llama zero-shot forecaster and Facebook Prophet Time Series model to support new and old users, respectively.
          - Optimized engines to handle heavy loads by providing separate queues for each one and by utilizing frequency and forecast horizon agnostic workarounds. Last recorded performance was 2500 forecasts in 8 seconds.
          - Provided accurate stock level predictions based on forecasted demands using flexible and reliable inventory optimization equations and assumptions.
          - Integrated various endpoints that utilize forecasting engines to estimate best sellers based on demand, stockouts based on consumption, and shortage quantities for idle operations per stock item.
      - name: Arabic ABSA for Traffic Services
        location: iSemantics'
        # summary: Aspect-Based Sentiment Analysis for Traffics Complains on X (Twitter)
        highlights:
          - Developed Classification/Summarization ABSA system to categorize users' feedback from X/Twitter into predefined topics, detect sentiments, and summarize services' drawbacks.
          - Leveraged pre-trained Arabic Camel-BERT and AraBART models for classification and sequence-to-sequence summarization, respectively.
          - Annotated 56K review tweets collected from Traffic Agency on X using BERTopic, OpenAI, and Llama-3. Employed OpenAI's gpt-4o-mini to summarization annotation.
          - Applied domain adaptation to refine tweet embeddings, utilized BERTopic to extract major topics from data and suggest topic labels, used hypothesis testing of proportions to estimate labeling accuracy, and employed majority voting to resolve conflicting labels, trained classification models using weighted loss to account for class imbalance.
          - Achieved 92 macro-averaged F1 score for Topic Classification, 95 macro-averaged F1 score for Sentiment Classification, 82 macro-averaged F1 score for ABSA system (Topic+Sentiment), and 79.8 ROUGE score for Text Summarization.
          - Hosted demo pipeline on HuggingFace Spaces for agencies to provide initial insights.
    skills:
      - label: Programming and Query Languages
        details: Python, HTML/CSS, SQL, Cypher
      - label: Developer Tools
        details: Git/GitHub, BitBucket, Jira, Docker, Postman
      - label: Databases and Indexes
        details: PostgreSQL, MS SQL, MongoDB, Neo4j, Qdrant, Pinecone, FAISS
      - label: AI Frameworks
        details: PyTorch, Stanza, Transformers, Sentence-Transformers, Adapters, LoRA, SciKit-learn, Weights & Biases, DVC, LangChain, LlamaIndex, FastAPI, Matplotlib, Plotly, Gradio, Pandas, Polars
      - label: Languages
        details: Arabic (Native), English (Fluent, American)
design:
  theme: engineeringresumes
  page:
    size: us-letter
    top_margin: 2cm
    bottom_margin: 2cm
    left_margin: 2cm
    right_margin: 2cm
    show_page_numbering: false
    show_last_updated_date: false
  colors:
    text: rgb(0, 0, 0)
    name: rgb(0, 0, 0)
    connections: rgb(0, 0, 0)
    section_titles: rgb(0, 0, 0)
    links: rgb(0, 0, 0)
    last_updated_date_and_page_numbering: rgb(128, 128, 128)
  text:
    font_family: XCharter
    font_size: 10pt
    leading: 0.6em
    alignment: justified
    date_and_location_column_alignment: right
  links:
    underline: true
    use_external_link_icon: false
  header:
    name_font_family: XCharter
    name_font_size: 24pt
    name_bold: false
    vertical_space_between_name_and_connections: 0.6cm
    vertical_space_between_connections_and_first_section: 0.8cm
    horizontal_space_between_connections: 0.4cm
    connections_font_family: XCharter
    separator_between_connections: "|"
    use_icons_for_connections: false
    alignment: center
  section_titles:
    type: with-full-line
    font_family: XCharter
    font_size: 1.2em
    bold: true
    small_caps: false
    line_thickness: 0.5pt
    vertical_space_above: 0.55cm
    vertical_space_below: 0.3cm
    line_type: with-full-line
  entries:
    date_and_location_width: 4.15cm
    left_and_right_margin: 0cm
    horizontal_space_between_columns: 0.1cm
    vertical_space_between_entries: 0.4cm
    allow_page_break_in_sections: true
    allow_page_break_in_entries: true
    short_second_row: false
    show_time_spans_in: []
  highlights:
    bullet: •
    top_margin: 0.25cm
    left_margin: 0cm
    vertical_space_between_highlights: 0.19cm
    horizontal_space_between_bullet_and_highlight: 0.3em
    summary_left_margin: 0cm
  entry_types:
    one_line_entry:
      template: "**LABEL:** DETAILS"
    education_entry:
      main_column_first_row_template: "**INSTITUTION**, DEGREE in AREA -- LOCATION"
      degree_column_template:
      degree_column_width: 1cm
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    normal_entry:
      main_column_first_row_template: "**NAME** -- **LOCATION**"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    experience_entry:
      main_column_first_row_template: "**POSITION**, COMPANY -- LOCATION"
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: DATE
    publication_entry:
      main_column_first_row_template: "**TITLE**"
      main_column_second_row_template: |-
        AUTHORS
        URL (JOURNAL)
      main_column_second_row_without_journal_template: |-
        AUTHORS
        URL
      main_column_second_row_without_url_template: |-
        AUTHORS
        JOURNAL
      date_and_location_column_template: DATE
locale:
  language: en
  phone_number_format: national
  page_numbering_template: NAME - Page PAGE_NUMBER of TOTAL_PAGES
  last_updated_date_template: Last updated in TODAY
  date_template: MONTH_ABBREVIATION YEAR
  month: month
  months: months
  year: year
  years: years
  present: present
  to: "--"
  abbreviations_for_months:
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - June
    - July
    - Aug
    - Sept
    - Oct
    - Nov
    - Dec
  full_names_of_months:
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
rendercv_settings:
  date: "2025-05-10"
```

check: https://enhancv.com/resources/resume-checker/ and https://www.resumego.net/resume-checker/
